from typing import BinaryIO, Protocol


class StorageProvider(Protocol):
    """定义业务层依赖的最小对象存储能力。"""

    def put(self, object_key: str, source: BinaryIO) -> None: ...

    def open(self, object_key: str) -> BinaryIO: ...

    def delete(self, object_key: str) -> None: ...

    def exists(self, object_key: str) -> bool: ...
