"""create chat usage table

Revision ID: 575175576c72
Revises: 578d92bbd61c
Create Date: 2026-08-13 16:12:03.177236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "575175576c72"
down_revision: Union[str, None] = "578d92bbd61c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("request_mode", sa.String(length=16), nullable=False),
        sa.Column("model_alias", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("provider_model", sa.String(length=128), nullable=True),
        sa.Column("prompt_key", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("total_tokens", sa.BigInteger(), nullable=True),
        sa.Column("latency_ms", sa.BigInteger(), nullable=False),
        sa.Column("time_to_first_token_ms", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("pricing_version", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status = 'success' AND finish_reason IS NOT NULL AND error_code IS NULL) OR (status IN ('failed', 'cancelled') AND finish_reason IS NULL AND error_code IS NOT NULL)",
            name="ck_chat_usages_terminal_fields",
        ),
        sa.CheckConstraint(
            "request_mode IN ('non_stream', 'stream')",
            name="ck_chat_usages_request_mode",
        ),
        sa.CheckConstraint(
            "status IN ('success', 'failed', 'cancelled')", name="ck_chat_usages_status"
        ),
        sa.CheckConstraint(
            "(estimated_cost IS NULL AND currency IS NULL AND pricing_version IS NULL) OR (estimated_cost IS NOT NULL AND currency IS NOT NULL AND pricing_version IS NOT NULL)",
            name="ck_chat_usages_cost_snapshot",
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name="ck_chat_usages_estimated_cost_non_negative",
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name="ck_chat_usages_input_tokens_non_negative",
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR output_tokens IS NULL OR total_tokens IS NULL OR total_tokens = input_tokens + output_tokens",
            name="ck_chat_usages_token_total",
        ),
        sa.CheckConstraint(
            "latency_ms >= 0", name="ck_chat_usages_latency_ms_non_negative"
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name="ck_chat_usages_output_tokens_non_negative",
        ),
        sa.CheckConstraint(
            "time_to_first_token_ms IS NULL OR time_to_first_token_ms >= 0",
            name="ck_chat_usages_ttft_ms_non_negative",
        ),
        sa.CheckConstraint(
            "total_tokens IS NULL OR total_tokens >= 0",
            name="ck_chat_usages_total_tokens_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_chat_usages_user_id_users",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", name="uq_chat_usages_request_id"),
    )
    op.create_index(
        "ix_chat_usages_status_created_at",
        "chat_usages",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_chat_usages_user_created_at",
        "chat_usages",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_usages")
    # ### end Alembic commands ###
